### ISSUE TITLE
ERROR: CTL:TIMEOUT X in u-boot

### ISSUE THREAD

**Issue by cbrake** [sysadminmike/freebsd-onion-omega2-build#2]
Hi,
I'm trying to load image via u-boot and getting:

```
Omega2 # fatload usb 0:1 1000000 /kernel.img
ERROR: CTL:TIMEOUT X
BBB_reset
usb_control_msg: request: 0xFF, requesttype: 0x21
value 0x0 index 0x0 length 0x0
```

Do you know what version of u-boot you were using?

When system boots, I see:

============================================
Onion Omega2 UBoot Version: 4.3.0.3

But when I enter u-boot command line, I see:

U-Boot 1.1.3 (Nov  8 2019 - 13:46:42)

So not sure what this module is running.

**Comment by sysadminmike** [comment]
Hi,
I have just had a look back at some of the 'screen shots' of the output - I think these were the versions:

Onion Omega2 UBoot Version: 4.3.0.3
U-Boot 1.1.3 (Oct 18 2016 - 17:29:05)

I dont recall upgrading UBoot stuff - its been a good few years since I looked at this.

I do remember having some grief with having to reset the usb and also finding the correct address to load the kernel to - have a look at the FreeBSD mips maillist from about 3 years ago and I think there is some more info about that there but from what i can rememberer it was a bit of black magic getting this address correct.

Omega2 #  fatload usb 0:1 0x80800000 kernel.MT7628_FDT.lzma.uImage

Sorry I cant be of more help.

**Comment by cbrake** [comment]
thanks for the info!
